[package]
name = "nes"
version = "0.1.0"
authors = ["Arun Kulshreshtha <kulshrax@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
env_logger = "0.8"
log = "0.4"
nom = "4.2.3"
structopt = "0.3"