[package]
name = "nes"
version = "0.1.0"
authors = ["Arun Kulshreshtha <kulshrax@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
env_logger = "0.6.1"
log = "0.4.6"
structopt = "0.2.15"